/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package perfunctory.secretary;

import io.micronaut.runtime.Micronaut;

public class App {

    public static void main(String[] args) {
        Micronaut.run(App.class);
    }
}
